version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: ExpenseTrackerTestDb
      MYSQL_USER: admintest
      MYSQL_PASSWORD: admintest123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
